# Generated by Django 4.0.3 on 2022-05-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekyc2',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
