# Generated by Django 4.0.3 on 2022-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0002_alter_ekyc2_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekyc2',
            name='name',
            field=models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd')], max_length=255),
        ),
    ]
