# Generated by Django 4.0.3 on 2022-05-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0003_alter_ekyc2_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekyc2',
            name='content',
        ),
    ]
