# Generated by Django 4.0.3 on 2022-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0004_remove_ekyc2_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekyc2',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
