# Generated by Django 4.0.3 on 2022-05-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0005_ekyc2_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ekyc2',
            old_name='name',
            new_name='gender',
        ),
    ]
