# Generated by Django 4.0.3 on 2022-05-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0007_remove_ekyc2_phone_ekyc2_income_ekyc2_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekyc2',
            name='income',
            field=models.IntegerField(default=True, max_length=100),
        ),
    ]
