# Generated by Django 4.0.3 on 2022-05-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0008_alter_ekyc2_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekyc2',
            name='income',
        ),
    ]
