# Generated by Django 4.0.3 on 2022-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0009_remove_ekyc2_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekyc2',
            name='uploadArea',
            field=models.FileField(default=True, upload_to='uploads/'),
        ),
    ]
