# Generated by Django 4.0.3 on 2022-05-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0010_ekyc2_uploadarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ekyc2',
            old_name='uploadArea',
            new_name='uploadedFile3',
        ),
    ]
