# Generated by Django 4.0.3 on 2022-05-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0011_rename_uploadarea_ekyc2_uploadedfile3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ekyc2',
            old_name='uploadedFile3',
            new_name='uploadedFileInfo5',
        ),
    ]
