# Generated by Django 4.0.3 on 2022-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0012_rename_uploadedfile3_ekyc2_uploadedfileinfo5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekyc2',
            name='uploadedFileInfo5',
        ),
        migrations.AddField(
            model_name='ekyc2',
            name='fileDetails3',
            field=models.FileField(default=True, upload_to='uploads/'),
        ),
    ]
