# Generated by Django 4.0.3 on 2022-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0013_remove_ekyc2_uploadedfileinfo5_ekyc2_filedetails3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekyc2',
            name='fileDetails3',
            field=models.ImageField(default=True, upload_to='uploads/'),
        ),
    ]
