# Generated by Django 4.0.3 on 2022-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0015_alter_ekyc2_filedetails3'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekyc2',
            name='income',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
