# Generated by Django 4.0.3 on 2022-05-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0020_alter_ekyc2_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekyc2',
            name='income',
            field=models.CharField(choices=[('Below BDT 1000', 'Below BDT 1000'), ('BDT 1001 - 5000', 'BDT 1001 - 5000'), ('BDT 5001 -10000', 'BDT 5001 -10000'), ('BDT 10,001 - 20,000', 'BDT 10,001 - 20,000'), ('BDT 20,001 - 50,000', 'BDT 20,001 - 50,000'), ('BDT 50,001 - 100,000', 'BDT 50,001 - 100,000'), ('BDT 100,001 - 200,000', 'BDT 100,001 - 200,000'), ('More than 200,000', 'More than 200,000')], default=True, max_length=100),
        ),
    ]
