# Generated by Django 4.0.3 on 2022-05-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc2', '0021_alter_ekyc2_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekyc2',
            name='fileDetails3',
        ),
        migrations.AddField(
            model_name='ekyc2',
            name='selfie',
            field=models.ImageField(default=True, upload_to='images'),
        ),
    ]
